swagger: '2.0'
basePath: /
host: localhost:8000
info:
  tile: 'dailycode Api:'
  version: 0.0.1
paths:
  /records/:
    get:
      description: Get dailycode records
      responses:
        200:
          description: Succeed to get records
produces:
  - applicaation/json
schemes:
  - http
  - https
